# Generated by Django 6.0.6 on 2026-06-27 09:48

from django.db import migrations, models


def create_initial_stats(apps, schema_editor):
    image_transformation_stats = apps.get_model("images", "ImageTransformationStats")
    image_transformation_stats.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTransformationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, verbose_name="nom de l'image")),
                ('transformed_at', models.DateTimeField(auto_now_add=True, verbose_name='date et heure')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], max_length=10, verbose_name='statut')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
            ],
            options={
                'verbose_name': "transformation d'image",
                'verbose_name_plural': "transformations d'images",
                'ordering': ['-transformed_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageTransformationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful_transformations', models.PositiveBigIntegerField(default=0, verbose_name="nombre total d'images transformées")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'compteur de transformations',
                'verbose_name_plural': 'compteur de transformations',
            },
        ),
        migrations.RunPython(create_initial_stats, migrations.RunPython.noop),
    ]
